<!DOCTYPE window [
        <!ELEMENT window (data|layout)*>
        <!ATTLIST window
                xmlns CDATA #REQUIRED
                caption CDATA #REQUIRED>
        <!ELEMENT data (collection)*>
        <!ELEMENT collection (fetchPlan|loader)*>
        <!ATTLIST collection
                class CDATA #REQUIRED
                id CDATA #REQUIRED>
        <!ELEMENT fetchPlan (#PCDATA)>
        <!ATTLIST fetchPlan
                extends CDATA #REQUIRED>
        <!ELEMENT loader (query)*>
        <!ATTLIST loader
                id CDATA #REQUIRED>
        <!ELEMENT query (#PCDATA)>
        <!ELEMENT layout (vbox)*>
        <!ELEMENT vbox (hbox|vbox|buttonsPanel)*>
        <!ATTLIST vbox
                align CDATA #REQUIRED
                spacing CDATA #REQUIRED>
        <!ELEMENT hbox (label|comboBox|table|button)*>
        <!ATTLIST hbox
                align CDATA #REQUIRED
                spacing CDATA #REQUIRED>
        <!ELEMENT label (#PCDATA)>
        <!ATTLIST label
                id CDATA #REQUIRED
                stylename CDATA #REQUIRED
                value CDATA #REQUIRED>
        <!ELEMENT comboBox (#PCDATA)>
        <!ATTLIST comboBox
                id CDATA #REQUIRED
                nullOptionVisible CDATA #REQUIRED
                stylename CDATA #REQUIRED
                textInputAllowed CDATA #REQUIRED>
        <!ELEMENT table (columns)*>
        <!ATTLIST table
                align CDATA #IMPLIED
                columnHeaderVisible CDATA #IMPLIED
                dataContainer CDATA #REQUIRED
                emptyStateLinkMessage CDATA #IMPLIED
                height CDATA #REQUIRED
                id CDATA #REQUIRED
                visible CDATA #IMPLIED
                width CDATA #REQUIRED>
        <!ELEMENT columns (column)*>
        <!ELEMENT column (#PCDATA)>
        <!ATTLIST column
                id CDATA #REQUIRED>
        <!ELEMENT button (#PCDATA)>
        <!ATTLIST button
                align CDATA #IMPLIED
                caption CDATA #REQUIRED
                id CDATA #REQUIRED>
        <!ELEMENT buttonsPanel (button)*>
        <!ATTLIST buttonsPanel
                id CDATA #REQUIRED
                alwaysVisible CDATA #REQUIRED
                align CDATA #REQUIRED>
        ]>
<window xmlns="http://jmix.io/schema/ui/window"
        caption="msg://application.caption">
    <data>
        <collection id="lexgraphInputsDc" class="com.company.test4.entity.LexgraphInput">
            <fetchPlan extends="_base"/>
            <loader id="lexgraphInputsDl">
                <query>
                    <![CDATA[select e from LexgraphInput e]]>
                </query>
            </loader>
        </collection>
        <collection id="lexgraphInputsDc_1" class="com.company.test4.entity.LexgraphInput">
            <fetchPlan extends="_base"/>
            <loader id="lexgraphInputsDl1">
                <query>
                    <![CDATA[select e from LexgraphInput e]]>
                </query>
            </loader>
        </collection>
        <collection id="magNumInputsDc" class="com.company.test4.entity.MagNumInput">
            <fetchPlan extends="_base"/>
            <loader id="magNumInputsDl">
                <query>
                    <![CDATA[select e from MagNumInput e]]>
                </query>
            </loader>
        </collection>
        <collection id="outputsDc" class="com.company.test4.entity.Output">
            <fetchPlan extends="_base"/>
            <loader id="outputsDl">
                <query>
                    <![CDATA[select e from Output_ e]]>
                </query>
            </loader>
        </collection>
    </data>

    <layout>
        <vbox spacing="true" align="MIDDLE_CENTER">
            <hbox spacing="true" align="TOP_CENTER">
                <label id="taskSelectLbl"
                       stylename="jmix-login-caption"
                       value="Select task"/>
                <comboBox id="tasksCbx"
                          nullOptionVisible="false"
                          stylename="jmix-login-locale"
                          textInputAllowed="false"/>
            </hbox>
            <vbox spacing="true" align="MIDDLE_CENTER">
                <hbox spacing="true" align="MIDDLE_CENTER">
                    <table id="lexgraphInputsTable" editable="true" dataContainer="lexgraphInputsDc" height="200px" width="200px" align="MIDDLE_CENTER" emptyStateLinkMessage="Add">
                        <columns>
                            <column id="Input" caption="String" editable="true"/>
                        </columns>
                    </table>
                    <table id="lexgraphInputsTable1" dataContainer="lexgraphInputsDc_1" height="200px" width="200px" emptyStateLinkMessage="Add"
                           align="MIDDLE_CENTER" editable="true">
                        <columns>
                            <column id="Input" caption="Substring" editable="true"/>
                        </columns>
                    </table>
                    <table id="magNumInputsTable" dataContainer="magNumInputsDc" height="200px" width="200px"
                           visible="false" editable="true" columnHeaderVisible="false">
                        <columns>
                            <column id="input" width="66px" editable="true"/>
                        </columns>
                    </table>

                </hbox>

                <hbox spacing="true" align="TOP_CENTER">
                    <button id="countBtn" caption="Count"/>
                </hbox>
                <hbox spacing="true" align="MIDDLE_CENTER">
                    <table id="outputsTable" dataContainer="outputsDc" height="200px" width="200px" align="MIDDLE_CENTER">
                        <columns>
                            <column id="Output"/>
                        </columns>
                    </table>
                </hbox>
                <buttonsPanel id="buttonsPanel"
                              alwaysVisible="true" align="MIDDLE_CENTER">
                    <button id="saveBtn" caption="Save" align="MIDDLE_CENTER"/>
                    <button id="exportBtn" caption="Export" align="MIDDLE_CENTER"/>
                    <fileStorageUpload id="uploadBtn" accept="*.txt"
                                       fileStoragePutMode="MANUAL"/>
                    <button id="importBtn" caption="Import" align="MIDDLE_CENTER"/>
                </buttonsPanel>

            </vbox>
        </vbox>
    </layout>
</window>